import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { MapContainer, Marker, Popup, TileLayer, useMap } from "react-leaflet";
import { trpc } from "../utils/trpc";
import BasicMapComponent from "../components/map/basic_map_component";
import dynamic from "next/dynamic";

const Home: NextPage = () => {
  const BasicMapComponent = dynamic(() => import("../components/map/basic_map_component"), {
    ssr: false,
    loading: () => <p>Loading...</p>
  });


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ height: "100%" }}>
        <BasicMapComponent />
      </div>
    </>
  );
};

export default Home;